server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://db:6432/hapi'
    username: hapi
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect
      hibernate.search.enabled: true
hapi:
  fhir:
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    default_encoding: json
    version: R4
    client_id_strategy: 'ANY'
    server_id_mode: 'UUID'
    implementationguides:
      r4_core:
        name: hl7.fhir.r4.core
        version: 4.0.1
        reloadExisting: false
        installMode: STORE_AND_INSTALL